# This is a basic workflow to help you get started with Actions

name: Compile Website

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master, build-action ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Switch to build branch
      run: git checkout -b build

    - name: Setup Ruby
      run: |
        sudo gem install bundler
        sudo gem install middleman
        bundle install
        sudo chmod -R +777 /var/lib/gems/2.5.0/gems/middleman-robots-1.3.5/

    - name: Build website
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        bundle exec middleman build

    - name: Upload website
      env:
        aws_access_key_id: ${{ secrets.aws_access_key_id }}
        aws_secret_access_key: ${{ secrets.aws_secret_access_key }}
        bucket: ${{ secrets.bucket }}
        region: ${{ secrets.region }}
      run: bundle exec middleman s3

    - name: invalidate
      uses: chetan/invalidate-cloudfront-action@v1.2
      env:
        DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
        PATHS: '/*'
        AWS_REGION: ${{ secrets.region }}
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
